### ISSUE TITLE
npm start  error

### ISSUE THREAD

**Issue by sheldonhu** [arterli/CmsWing#29]
/home/ubuntu/CmsWing-1.1.0/src/config/adapter/view.js:213
            env.addFilter("getmodelfield", async(id, model_id, field, callback) => {
                                                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/CmsWing-1.1.0/src/config/adapter.js:51:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by arterli** [comment]
升级node版本，7.6以上
