### ISSUE TITLE
NPM START 错误

### ISSUE THREAD

**Issue by wickedcode01** [arterli/CmsWing#34]
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by wickedcode01** [comment]
C:\Users\****\Desktop\cmswing\node_modules\core-util-is\lib\util.js:1
(function (exports, require, module, __filename, __dirname) {

**Comment by wickedcode01** [comment]
node版本最新的v10.14.2

**Comment by wickedcode01** [comment]
npm install报的warning如下
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN CMSWing@1.3.7 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 3013 packages in 4.689s
found 12 vulnerabilities (2 low, 10 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by wickedcode01** [comment]
npm的问题好像，每次npm install之后报的错都不一样

**Comment by wickedcode01** [comment]
解决了！第一次NPM的时候电脑崩了重启了，导致莫名问题，整个项目删掉，重新NPM即可解决
