### ISSUE TITLE
运行报graphql相关错误

### ISSUE THREAD

**Issue by kavil** [arterli/CmsWing#60]
Window10系统  
node 14.9.3

$ npm run dev

> cmswing@2.0.1 dev D:\playtime\CmsWing
> egg-bin dev

[egg-ts-helper] create typings\app\extend\context.d.ts (3ms)
[egg-ts-helper] create typings\app\extend\helper.d.ts (5ms)   
[egg-ts-helper] create typings\app\controller\index.d.ts (4ms)
[egg-ts-helper] create typings\app\middleware\index.d.ts (3ms)
[egg-ts-helper] create typings\app\model\index.d.ts (5ms)
[egg-ts-helper] create typings\config\index.d.ts (26ms)
[egg-ts-helper] create typings\config\plugin.d.ts (1ms)
[egg-ts-helper] create typings\app\service\index.d.ts (2ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)        
2022-11-08 00:04:33,981 INFO 8392 [master] node version v14.19.3
2022-11-08 00:04:33,982 INFO 8392 [master] egg version 3.3.3
2022-11-08 00:04:35,242 INFO 14168 [egg-sequelize] Not overriding built-in method from model attribute: where
2022-11-08 00:04:35,271 INFO 14168 [egg-sequelize] Not overriding built-in method from model attribute: where
2022-11-08 00:04:35,274 INFO 14168 [egg-sequelize] Not overriding built-in method from model attribute: where
2022-11-08 00:04:35,393 ERROR 14168 nodejs.Error: Body must be a string. Received: undefined.
    at devAssert (D:\playtime\CmsWing\node_modules\graphql\jsutils\devAssert.js:12:11)
    at new Source (D:\playtime\CmsWing\node_modules\graphql\language\source.js:32:32)
    at new Parser (D:\playtime\CmsWing\node_modules\graphql\language\parser.js:98:9)
    at Object.parse (D:\playtime\CmsWing\node_modules\graphql\language\parser.js:31:18)
    at Object.<anonymous> (D:\playtime\CmsWing\node_modules\graphql-tools\dist\stitching\introspectSchema.js:40:42)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)

**Comment by arterli** [comment]
依赖的问题，重新安装下依赖，或者使用 yarn 安装试试

**Comment by kavil** [comment]
升级node到16解决
